sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_f6eb08e611d1_key -iv $encrypted_f6eb08e611d1_iv -in multi-k8s-363607-ac150cf2bba5.json.enc -out multi-k8s-363607-ac150cf2bba5.json -d
  # Install google cloud sdk
  - curl https://skd.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
